name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get Deps
      run: go get -d -v ./...

    - name: Build
      run: |
          GOOS=linux   GOARCH=amd64 go build -o bin/discord-embed-supercharger-linux-amd64
          GOOS=linux   GOARCH=386 go build -o bin/discord-embed-supercharger-linux-386
          GOOS=linux   GOARCH=arm go build -o bin/discord-embed-supercharger-linux-arm
    
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: bin/

  deploy:
    name: Deploy binary
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: bin/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: scp
        run: |
          scp ./bin/discord-embed-supercharger-linux-386 github@${{ secrets.DEPLOY_SERVER_HOST }}:
      
      - name: restart process
        run: |
          ssh github@${{ secrets.DEPLOY_SERVER_HOST }} ${{ secrets.DEPLOY_SERVER_SCRIPT }}
